### ISSUE TITLE
Not clear how to influence the sequence of login-modules

### ISSUE THREAD

**Issue by darkroastjava** [wildfly-swarm/docs.wildfly-swarm.io#2]
The documentation mentions that when using java properties, a "KEY" needs to be defined for each login-module:

> "Any property that has KEY listed in its name indicates that a user-supplied key or identifier should be used in that segment of the name."

However as it seems java properties are not processed in the order in which they appear in a properties file. 

For the login-modules (e.g.) it is crucial to define in which order the should be executed. In XML the order is defined by the order of the <login-module> XML elements. The documentation on the security fraction does not explain how to achieve this.

**Comment by kenfinnigan** [comment]
Please raise an issue in JIRA at http://issues.jboss.org/browse/THORN

Issues on this repo shouldn't be active as we don't track issues in GitHub for this repo.
